export const categories = [
  'All Categories',
  'Arts, Media & Entertainment',
  'Food & Catering',
  'Hotel & Hospitality',
  'Shopping',
  'Financial Services',
  'Tour, Travel & Transport',
  'Health',
  'Sports and Leisure',
  'Beauty & Spa',
  'Event Oraganizers',
  'Education & Training',
  'Automotive & Gas stations',
  'Night Life',
  'Import/ Export',
  'Construction and Engineering',
  'Local Services',
  'Religious Organizations',
  'Governmental Institutions',
  'NGOs & Humanitarian',
];
